name: "Nix Build"
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: meta-introspector/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - name: Install Nix
        uses: meta-introspector/install-nix-action@v22
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - name: Build the flake
        run: nix build
